config/routes.rb
Todoer::Application.routes.draw do

  root :to => 'todos#index'

  get 'todos/new' => 'todos#new', as: 'new_todo'

  get 'todos' => 'todos#index', as: 'todos'

  post 'todos' => 'todos#create'

  get 'todos/:id' => 'todos#show', as: 'todo'

  delete 'todos/:id' => 'todos#delete', as: 'todo'

  post 'todos/undo' => 'todos#restore', as: 'restore_todo'

end

app/models/todo.rb
class Todo
  include Mongoid::Document

  field :title, type: String
  field :due_date, type: DateTime
  field :has_due_time, type: Boolean
  field :description, type: String


  validates :title, :due_date, :presence => true

  # Checks if the due_date (and if existing due_time) is already past
  def overdue?
    due_date.past?
  end

  def datetime
    if has_due_time
      self.date + " " + self.time
    else
      self.date
    end
  end

  def date
    I18n.localize(due_date.to_date)
  end

  def time
    I18n.localize(due_date, :format => :'time')
  end

  def description_with_size(size)
    if description.length > size
      description.first(size) + '...'
    else
      description.first(size)
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale


  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    { :locale => I18n.locale }
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  @@backup = nil


  def new
  end

  # Passes an array with all to-dos to list them
  def index
    @todos = Todo.all.sort{ |a,b| a.due_date <=> b.due_date }
  end

  # Passes the to-do that shall be displayed
  def show
    @todo = Todo.find(params[:id])
  end

  # Passes the to-do that shall be edited
  def edit
    @todo = Todo.find(params[:todo])
  end

  # Updates the to-do with the new data if possible, otherwise redirects to the 'edit' form
  def update
    #todo not yet done
  end

  # Deletes a to-do with the same id
  def delete
    @todo = Todo.find(params[:id])
    @@backup = @todo.clone
    if @todo.destroy
      flash[:type] = 'success'
      flash[:title] = t(:successful_delete_todo, :todo => @todo.title)
      #todo that ain't clean! v
      flash[:options] = {:content => t(:restore_button), :class => 'btn btn-small pull-right', :href => restore_todo_path, :method => 'post'}
      redirect_to todos_path
    else
      flash[:type] = 'error'
      flash[:title] = t(:unsuccessful_delete_todo, :todo => @todo.title)
      redirect_to todos_path
    end
  end

  # Creates the to-do if possible, otherwise it redirects to the creation aka 'new' form
  def create
    @new_todo = Todo.new
    @new_todo.title = params[:todo][:title]
    @new_todo.description = params[:todo][:description]
    @new_todo.has_due_time = params[:todo][:has_due_time]
    if @new_todo.has_due_time
      @new_todo.due_date = DateTime.new(params[:todo]['due_date(1i)'].to_i,
                                        params[:todo]['due_date(2i)'].to_i,
                                        params[:todo]['due_date(3i)'].to_i,
                                        params[:todo]['due_time(4i)'].to_i-1,
                                        params[:todo]['due_time(5i)'].to_i)
      # ---------------DEV NOTICE------------------
      # Die Lokalisation fick mich im Moment. Iwie muss ich DateTime sagen, dass es
      # auch wenn es versteht dass alle zeiten in der +01:00 Zeitzone sind nicht mit
      # einer Stunde addiert werden müssen
    else
      @new_todo.due_date = DateTime.new(params[:todo]['due_date(1i)'].to_i,
                                        params[:todo]['due_date(2i)'].to_i,
                                        params[:todo]['due_date(3i)'].to_i)
    end

    if @new_todo.save
      flash[:type] = 'success'
      flash[:title] = t(:successful_create_todo, :todo => @new_todo.title)
      redirect_to todos_path
    else
      flash[:type] = 'error'
      flash[:title] = t(:unsuccessful_create_todo)
      render :new
    end
    # ---------------DEV NOTICE------------------
    # im html wird das Symbol :to-do (ohne -) verwendet.  (folglich immer ohne - ;))
    # hier verwende ich @new_todo
    # würde ich auch hier @to-do verwenden, so würde bei einem 'render :new' die vorher eingegebenen formulardaten
    # wiederverwendet werden. das ist aber nicht möglich da ich vom Model unterschiedliche felder im Formular verwende
    # deshalb würde ich einen error erhalten und verzichte vorerst auf die formularwiederherstellung durch
    # verwendung von @new_to-do statt @to-do
  end

  # Restores the latest deleted to-do that has been backup'd in the global backup variable
  def restore
    if @@backup.save
      flash[:type] = 'success'
      flash[:title] = t(:successful_restore_todo, :todo => @@backup.title)
      @@backup = nil
      redirect_to todos_path
    else
      flash[:type] = 'error'
      flash[:title] = t(:unsuccessful_restore_todo)
      redirect_to todos_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Creates a alert based on bootstrap
  # possible types are: 'block', 'success', 'error' or 'info'
  # options hash can be used to create an additional button by setting:
  # :content as button text
  # :href as buttons link
  # :class as class
  # :method as get, post, delete or update
  def create_alert_field(type, title = nil, message = nil, options = {})
    t1 = content_tag :h4, title
    t2 = content_tag :h5, message
    bb = button_to(options[:content], options[:href], :class => options[:class], :method => options[:method]) unless options == nil || options.empty?
    t3 = content_tag :a, 'x', :class => 'close', :'data-dismiss' => 'alert'
    t1 = t1.concat(bb)
    t4 = t1.concat(t2)
    t5 = t3.concat(t4)

    content_tag :div, t5, :class => "alert alert-#{type}"
  end

end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Todoer</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>

<body>

  <div class="container">

    <div class="hero-unit">
      <h1><%= @page_title %></h1>
      <p class='lead'><%= @page_lead_text %></p>
      <p class="pull-right">
        <%= link_to(image_tag('flags/de.png'), '?locale=de') %>
        <%= link_to(image_tag('flags/gb.png'), '?locale=en') %>
      </p>
    </div>

    <div class="container">
      <ul class="nav nav-pills">
        <li class="<%= 'active' if @page == 'index' %>"><a href="<%= todos_path %>"><%= t(:page_menu_home) %></a></li>
        <li class="<%= 'active' if @page == 'new' %>"><a href="<%= new_todo_path %>"><%= t(:page_menu_new) %></a></li>
        <li></li>
      </ul>
    </div>

    <%= create_alert_field(flash[:type], flash[:title], flash[:message], flash[:options]) if flash[:type] %>

    <%= yield %>

    <hr>
    <footer>
      <p>&copy;<%= t(:page_copyright) %></p>
    </footer>

  </div>

</body>
</html>

app/views/todos/index.html.erb
<% @page = 'index' %>
<% @page_title = t(:page_index_title) %>
<% @page_lead_text = t(:page_index_lead) %>


<table width='100%' class="table table-striped">
  <tr>
    <th class='span2'><%= t(:table_title) %></th>
    <th class='span2'><%= t(:table_due_date) %></th>
    <th class='span4'><%= t(:table_description) %></th>
    <th class='span1'><%= t(:table_actions) %></th>
  </tr>
  <% @todos.each do |todo| %>
    <tr>
      <td><%= todo.title %></td>
      <td><%= todo.datetime %>
        <% if todo.overdue? %>
          <span class="label label-important pull-right"> <%= t(:table_tag_overdue) %></span>
        <% end %>
      </td>
      <td><%= todo.description_with_size(20) %></td>
      <td>
        <div class="btn-toolbar">
          <div class="btn-group">
            <%= link_to raw('<i class="icon icon-edit"></i>'), todo_path(todo), :class => 'btn' %>
            <%= link_to raw('<i class="icon icon-remove icon-white"></i>'), todo, :class => "btn btn-danger", :method => :delete %>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<% @page = 'new' %>
<% @page_title = t(:page_new_title) %>
<% @page_lead_text = t(:page_new_lead) %>


<%= form_for(:todo, :url => "/todos?locale=" + params[:locale], :html => { :class => 'form-horizontal' } ) do |f| %>

  <div class="control-group">
    <%= f.label( t(:new_title), :class => 'control-label') %>
    <div class="controls">
      <%= f.text_field(:title, :placeholder => t(:new_title), :class => 'input-block-level') %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label( t(:new_due_date), :class => 'control-label') %>
    <div class="controls">
      <%= f.date_select(:due_date, :class => 'input-block-level', :order => [:day, :month, :year], :start_year => Date.today.year)%>
    </div>
  </div>

  <div class="control-group">
    <div class='control-group'>
      <%= f.label( t(:new_due_time), :class => 'control-label') %>
      <div class="controls">
        <div id="due_date_switch"  class="switch switch-mini" data-on-label="<i class='icon-ok icon-white'></i>" data-off-label="<i class='icon-remove'></i>">
          <%= f.check_box :'has_due_time' %>
        </div>
      </div>
    </div>
    <div id="due_time_form" class='collapse'>
      <div class="controls">
        <%= f.time_select(:due_time, :class => 'input-block-level', :order => [:minute, :hour]) %>
      </div>
    </div>
  </div>

  <div class="control-group">
    <%= f.label( t(:new_description), :class => 'control-label') %>
    <div class="controls">
      <%= f.text_area(:description, :placeholder => t(:new_description), :rows => '3', :class => 'input-block-level') %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit( t(:new_submit), :class => 'btn btn-large btn-primary') %>
    <%= link_to( t(:new_cancel), todos_path, :class => 'btn') %>
  </div>

<% end %>

<script>
  $('#due_date_switch').on('switch-change', function (e, data) {
    var $el = $(data.el), value = data.value;
    if(value) {
      $('#due_time_form').collapse('show');
    } else {
      $('#due_time_form').collapse('hide');
    }
  });
</script>

app/views/todos/show.html.erb
<% @page = 'show' %>
<% @page_title = 'Check it out!' %>
<% @page_lead_text = 'Isn`t it sweet?' %>

<%= @todo.title %>